language: ruby
bundler_args: --quiet
os:
  - linux
  - osx
rvm:
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.3.0
  - 2.3.1
  - ruby-head
script: "bundle exec rake"
env: RUBY_GC_TUNE=200 RUBY_GC_TUNE_DEBUG=1 RUBY_GC_SYNC_ALWAYS=1
gemfile:
  - Gemfile
notifications:
  recipients:
    - info@bearmetal.eu
branches:
  only:
    - master
